spring.application.name=livrolivre
server.port=8080

spring.cloud.gcp.firestore.project-id=openlib-database
spring.cloud.gcp.firestore.credentials.location=file:classpath:livrolivre-prod-3ab97-firebase-adminsdk-fbsvc-ab9b4bb8f2.json

firebase.config-path=classpath:livrolivre-prod-3ab97-firebase-adminsdk-fbsvc-ab9b4bb8f2.json

server.error.include-message=always
spring.main.allow-bean-definition-overriding=true