spring.application.name=livrolivre
server.port=8080

spring.cloud.gcp.firestore.project-id=livrolivre-3ab97
spring.cloud.gcp.firestore.credentials.location=classpath:livrolivre-dev-3ab97-firebase-adminsdk-fbsvc-aa5bbde648.json

firebase.config-path=classpath:livrolivre-dev-3ab97-firebase-adminsdk-fbsvc-aa5bbde648.json

server.error.include-message=always
spring.main.allow-bean-definition-overriding=true