spring.application.name=livrolivre
server.port=8080

spring.cloud.gcp.firestore.project-id=${FIREBASE_PROJECT_ID}
spring.cloud.gcp.firestore.credentials.location=${firebase.config-path}

firebase.config-path=${firebase.config-path}

server.error.include-message=always
spring.main.allow-bean-definition-overriding=true